#!/bin/sh
#
# /etc/init.d/activemq -- startup script for the ActiveMQ
#
# Written by Fred Dixon <ffdixon@bigbluebutton.org>
# Based on the tomcat6 init script.
# Written by Miquel van Smoorenburg <miquels@cistron.nl>.
# Modified for Debian GNU/Linux	by Ian Murdock <imurdock@gnu.ai.mit.edu>.
# Modified for Tomcat by Stefan Gybas <sgybas@debian.org>.
# Modified for Tomcat6 by Thierry Carrez <thierry.carrez@ubuntu.com>.
#
### BEGIN INIT INFO
# Provides:          activemq
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start ActiveMQ.
# Description:       Start the ActiveMQ service.
### END INIT INFO

set -e 

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=activemq
DESC="Apache ActiveMQ service"
DAEMON=/usr/bin/jsvc
ACTIVEMQ_HOME=/usr/share/$NAME
DEFAULT=/etc/default/$NAME

if [ `id -u` -ne 0 ]; then
	echo "You need root privileges to run this script"
	exit 1
fi
 
# Make sure activemq is started with system locale
if [ -r /etc/default/locale ]; then
	. /etc/default/locale
	export LANG
fi

. /lib/lsb/init-functions
. /etc/default/rcS


# The following variables can be overwritten in $DEFAULT

# The first existing directory is used for JAVA_HOME (if JAVA_HOME is not
# defined in $DEFAULT)
JDK_DIRS="/usr/lib/jvm/java-6-openjdk /usr/lib/jvm/java-6-sun /usr/lib/jvm/java-1.5.0-sun /usr/lib/j2sdk1.5-sun /usr/lib/j2sdk1.5-ibm /usr/lib/j2sdk1.4-sun /usr/lib/j2sdk1.4-blackdown /usr/lib/j2se/1.4 /usr/lib/j2sdk1.4-ibm /usr/lib/j2sdk1.3-sun /usr/lib/j2sdk1.3-blackdown /usr/lib/jvm/java-gcj /usr/lib/kaffe"

# Look for the right JVM to use
for jdir in $JDK_DIRS; do
    if [ -r "$jdir/bin/java" -a -z "${JAVA_HOME}" ]; then
        JAVA_HOME="$jdir"
    fi
done
export JAVA_HOME

# Output file
if [ -z "$OUT_FILE" ]; then
	OUT_FILE=/var/log/activemq.out
fi

# End of variables that can be overwritten in $DEFAULT


# overwrite settings from default file
if [ -f "$DEFAULT" ]; then
	. "$DEFAULT"
fi

if [ ! -f "$ACTIVEMQ_HOME/bin/run.jar" ]; then
	log_failure_msg "$NAME is not installed"
	exit 1
fi

if [ ! -f "$DAEMON" ]; then
	log_failure_msg "missing $DAEMON"
	exit 1
fi

JAVA_OPTS="$JAVA_OPTS -Xmx64M -Dcom.sun.management.jmxremote -Dorg.apache.activemq.UseDedicatedTaskRunner=true -Dactivemq.classpath=$ACTIVEMQ_HOME/conf -Dactivemq.home=$ACTIVEMQ_HOME -Dactivemq.base=$ACTIVEMQ_HOME -jar $ACTIVEMQ_HOME/bin/run.jar"

# Set juli LogManager if logging.properties is provided
#if [ -r "$ACTIVEMQ_BASE"/conf/logging.properties ]; then
#  JAVA_OPTS="$JAVA_OPTS "-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager" "-Djava.util.logging.config.file="$ACTIVEMQ_BASE/conf/logging.properties"
#fi

# Define other required variables
ACTIVEMQ_PID="/var/run/$NAME.pid"

case "$1" in
  start)
	if [ -z "$JAVA_HOME" ]; then
		log_failure_msg "no JDK found - please set JAVA_HOME"
		exit 1
	fi

	if [ ! -d "$ACTIVEMQ_HOME/conf" ]; then
		log_failure_msg "invalid ACTIVEMQ_HOME: $ACTIVEMQ_HOME"
		exit 1
	fi

	log_daemon_msg "Starting $DESC" "$NAME"
	if start-stop-daemon --start --test --pidfile "$ACTIVEMQ_PID" \
		--startas "$JAVA_HOME/bin/java" \
		>/dev/null; then

		start-stop-daemon --start --background --make-pidfile --pidfile $ACTIVEMQ_PID \
			--startas $JAVA_HOME/bin/java -- $JAVA_OPTS start 
		sleep 5

		# Because we pushed it into the background, we need to check it's status
        	if start-stop-daemon --test --start --pidfile "$ACTIVEMQ_PID" --startas "$JAVA_HOME/bin/java" >/dev/null; then
			log_end_msg 1
		else
			log_end_msg 0
		fi
	else
	        log_progress_msg "(already running)"
		log_end_msg 0
	fi
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
        if start-stop-daemon --start --test --pidfile "$ACTIVEMQ_PID" \
		--startas "$JAVA_HOME/bin/java" \
		>/dev/null; then
		log_progress_msg "(not running)"
	else
		start-stop-daemon --stop --pidfile $ACTIVEMQ_PID \
			--startas $JAVA_HOME/bin/java 
		rm $ACTIVEMQ_PID
		sleep 5
	fi
	log_end_msg 0
	;;
   status)
        if start-stop-daemon --start --test --pidfile "$ACTIVEMQ_PID" \
		--startas "$JAVA_HOME/bin/java" \
		>/dev/null; then

		if [ -f "$ACTIVEMQ_PID" ]; then
		    log_success_msg "$DESC is not running, but pid file exists."
			exit 1
		else
		    log_success_msg "$DESC is not running."
			exit 3
		fi
	else
		log_success_msg "$DESC is running with pid `cat $ACTIVEMQ_PID`"
	fi
        ;;
  restart|force-reload)
        if start-stop-daemon --test --stop --pidfile "$ACTIVEMQ_PID" \
		--startas "$JAVA_HOME/bin/java" \
		>/dev/null; then
		$0 stop
		sleep 1
	fi
	$0 start
	;;
  *)
	log_success_msg "Usage: $0 {start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
